### ISSUE TITLE
Can you support Traditional Chinese?

### ISSUE THREAD

**Issue by hkkane** [nlgxzef/Labrune#1]
Can't see it

![cap](https://user-images.githubusercontent.com/16114400/68113926-d5fa3080-ff2f-11e9-84bc-b99fc0cc63c1.jpg)

**Comment by nlgxzef** [comment]
v2.0.0.100 adds character set (language histogram) support.

![image](https://github.com/nlgxzef/Labrune/assets/1937572/3c9016d3-c509-4da2-92d5-8a2716584657)
