### ISSUE TITLE
Russian and other non-English characters languages.

### ISSUE THREAD

**Issue by AlexandrR29** [nlgxzef/Labrune#3]
In 10118 version NFSUC crack maked Chinese reliase group. Russian sound in the story movies not support. In Language Editor i`m opened Chinese subtitles .bin file and replaced on russian text. But in the game  characters visiable as "questchion simbols" Editor not support non - English characters in texts? Supporting added next Editor updates?

From Russian NFS fans with kind regards.

Alexandr.

**Comment by vanillazephyr** [comment]
Man, if you can't write words in english properly, why you asking something? You can use google translator for it. English language isn't too hard. I'm russian too and i advice you to learn language, because it hard to understand your request.

**Comment by HarGabt** [comment]
@AlexandrR29 @vanillazephyr New version with Cyrillic characters has just been released!
